apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-workflows
  repo: https://charts.akuity.io
  includeCRDs: true
  namespace: argo
  version: 1.2.0
  valuesFile: values.yaml
