apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-terraform
  namespace: wf
  labels:
    example: 'true'
spec:
  entrypoint: tf-run
  arguments:
    parameters:
    - name: wf-configmap-name
      value: wf-defaults-cm
  templates:
  - name: tf-run
    inputs:
      parameters:
      - name: git-url
        valueFrom:
          configMapKeyRef:
            name: '{{workflow.parameters.wf-configmap-name}}'
            key: tf-git-url
      - name: git-revision
        valueFrom:
          configMapKeyRef:
            name: '{{workflow.parameters.wf-configmap-name}}'
            key: tf-git-revision
      artifacts:
        - name: git-repo
          path: /src
          git:
            repo: '{{inputs.parameters.git-url}}'
            revision: '{{inputs.parameters.git-revision}}'
    metadata: {}
    containerSet:
      containers:
      - name: init
        image: 'hashicorp/terraform:1.2.6'
        workingDir: /src/test-1/tf
        command:
        - terraform
        args:
        - init
        resources: {}
      - name: main
        dependencies: ["init"]
        image: 'hashicorp/terraform:1.2.6'
        workingDir: /src/test-1/tf
        command:
        - terraform
        args:
        - plan
        resources: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowSuccess
  workflowMetadata:
    labels:
      example: 'true'
