apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-terraform
  namespace: wf
  labels:
    example: 'true'
spec:
  entrypoint: tf-run
  arguments:
    parameters:
    - name: wf-configmap-name
      value: wf-defaults-cm
  templates:
  - name: tf-run
    inputs:
      parameters:
      - name: git-url
        valueFrom:
          configMapKeyRef:
            name: '{{workflow.parameters.wf-configmap-name}}'
            key: tf-git-url
      - name: git-revision
        valueFrom:
          configMapKeyRef:
            name: '{{workflow.parameters.wf-configmap-name}}'
            key: tf-git-revision
      - name: git-path
        valueFrom:
          configMapKeyRef:
            name: '{{workflow.parameters.wf-configmap-name}}'
            key: tf-git-path
      artifacts:
        - name: git-repo
          path: '{{inputs.parameters.git-path}}'
          git:
            repo: '{{inputs.parameters.git-url}}'
            revision: '{{inputs.parameters.git-revision}}'
    metadata: {}
    container:
      name: main
      image: 'hashicorp/terraform:1.2.6'
      command:
      - terraform
      args:
      - version
      resources: {}
  ttlStrategy:
    secondsAfterCompletion: 300
  podGC:
    strategy: OnWorkflowSuccess
  workflowMetadata:
    labels:
      example: 'true'
